version: '3.6'
services:
  telegraf:
    image: telegraf:1.18-alpine
    container_name: prjctr_telegraf
    volumes:
      - ./etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    depends_on:
      - influxdb
      - mongodb
      - elasticsearch
      - nginx
      - php
    links:
      - influxdb
      - mongodb
      - elasticsearch
      - nginx
      - php
    ports:
      - '127.0.0.1:8125:8125/udp'
  influxdb:
    image: influxdb:1.8-alpine
    container_name: prjctr_influxdb
    env_file: .env
    ports:
      - '127.0.0.1:8086:8086'
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb
  grafana:
    build:
      dockerfile: ./docker/grafana/Dockerfile
      context: .
    container_name: prjctr_grafana
    depends_on:
      - influxdb
    env_file: .env
    links:
      - influxdb
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./etc/grafana/provisioning/:/etc/grafana/provisioning/
      - ./var/lib/grafana/dashboards/:/var/lib/grafana/dashboards/
  mongodb:
      container_name: prjctr_mongodb
      image: mongo:4.2.19
      env_file: .env
      ports:
        - "127.0.0.1:27017:27017"
  elasticsearch:
    container_name: prjctr_elasticsearch
    image: elasticsearch:8.1.3
    environment:
      - discovery.type=single-node
      - node.name=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ports:
      - "127.0.0.1:9200:9200"
  php:
    container_name: prjctr_php
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    working_dir: /var/www
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./var/www:/var/www/
      - ./etc/php-fpm.d/:/usr/local/etc/php-fpm.d/
    env_file:
      - .env
    links:
      - elasticsearch
      - mongodb
    depends_on:
      - elasticsearch
      - mongodb
  nginx:
    container_name: prjctr_nginx
    image: nginx:1.21.6
    ports:
      - "80:80"
      - "8080:80"
    volumes:
      - ./var/www:/var/www/
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/nginx/fastcgi_params:/etc/nginx/fastcgi_params
    depends_on:
      - php
    links:
      - php
volumes:
  grafana_data: {}
  influxdb_data: {}